auto: true
permalink: /blog/:year/:month/:title/
url: http://colaborativa.eu
paginate: 1
version: 1.0

titulo: Colaborativa.eu
subtitulo: { es: Estrategias y herramientas para transformar ciudades, en: Strategies and tools for transforming cities}
navegacion: { es: Navegación principal, en: Main navigation}
navegacion-blog: { es: Artículos, en: Articles, url: blog }
navegacion-proyectos: { es: Proyectos, en: Projects}
navegacion-equipo: { es: Equipo, en: Team, url: equipo }
navegacion-blog-todos: { es: /blog/todos/, en: /es/blog/all/}

footer-mapa: { es: Mapa, en: Map}
footer-content-somos-opensource: { es: Somos una empresa de código abierto , en: We are an open source company }
footer-content-somos-opensource-url: { url: https://github.com/colaborativa }
footer-content-opensource: { es: está compartido bajo, en: of our website code is shared under }
footer-content-opensource-url: { url: http://www.opensource.org/licenses/MIT, es: licencia MIT, en: the MIT License}
footer-content-copyleft: { es: los textos e imágenes bajo licencia, en: text and images are licensed under}
footer-content-copyleft-url: { url: http://creativecommons.org/licenses/by/3.0/, es: CC BY 3.0., en: CC BY 3.0.}
footer-content-codigofuente-url: { url: https://github.com/colaborativa/colaborativa.github.com/, es: El código fuente de nuestra web, en: The source code }
footer-content-disenado: { es: "Diseñado y hecho en", en: Design and made }
footer-content-hechocon: { es: Hecho con, en: Made with }
footer-content-hechocon-tools: { github: "github pages", github-url: "http://pages.github.com/", jekyll: "jekyll", jekyll-url: "https://github.com/mojombo/jekyll/wiki/", sass: "sass", sass-url: "http://sass-lang.com/", compass: "Compass", compass-url: "http://compass-style.org/", glyphish: "Glyphish icons", glyphish-url: "http://glyphish.com/"  }
footer-content-anade: { es: Descarga tarjeta, en: Add contact }
colaborativa_datos: { email: "info@colaborativa.eu", tel: "+34 957 78 21 64", street_address: "<span class='adicional'>Calle</span> Marroquíes 2", postal_code: "14001", locality: "Córdoba", region: "Andalucía", country: "España", continent: "Europa"}

enlaces-sociales-facebook: { url: http://www.facebook.com/pages/Colaborativa/129415973823832, es: Facebook, en: Facebook}
enlaces-sociales-twitter: { url: http://twitter.com/colaborativaeu, es: Twitter, en: Twitter, profile: @colaborativaeu }
enlaces-sociales-linkedin: { url: http://www.linkedin.com/company/colaborativa, es: linkedIn, en: linkedIn }
enlaces-sociales-google: { url: https://plus.google.com/114949886506494087353, es: Google+, en: Google+ }
enlaces-sociales-pinterest: { url: http://pinterest.com/, es: Pinterest, en: Pinterest }
enlaces-sociales-flickr: { url: http://www.flickr.com/photos/50381188@N06/, es: Fotos, en: Pictures}
enlaces-sociales-youtube: { url: http://www.youtube.com/user/colaborativaeu, es: Videos, en: Videos}
enlaces-sociales-issuu: { url: http://www.issuu.com/colaborativa, es: Docs, en: Docs}
enlaces-sociales-github: { url: http://www.github.com/colaborativa, es: Código, en: Code}

listado-colaborativos-titulo: { es: Colaborativos, en: Colaborativos}
listado-colaborativos-subtitulo: { es: ¿Quiénes somos?, en: Who are we?}

listado-colaboradores-titulo: { es: Colaboradores, en: Colaboradores}
listado-colaboradores-subtitulo: { es: ¿Con quién colaboramos?, en: Who we work with?}

listado-articulos-autor-titulo: { es: Artículos de este autor, en: Articles from this author }
listado-articulos-autor-subtitulo: { es: en nuestro blog, en: in our blog}

listado-articulos-categorias-titulo: { es: Algunos proyectos, en: Some projects}
listado-articulos-categorias-subtitulo: { es: relacionados con este artículo, en: related with this article}

listado-articulos-relacionados-titulo: { es: Otros artículos en nuestro blog, en: Other articles in our blog}
listado-articulos-relacionados-subtitulo: { es: que podrían interesarte, en: that may interest you}

listado-articulos-proyecto-titulo: { es: Últimos 5 artículos en el Blog, en: Last 5 articles}
listado-articulos-proyecto-subtitulo: { es: sobre este proyecto, en: about this project}

listado-proyectos-categorias-titulo: { es: ¿Qué hacemos?, en: What we do }
listado-proyectos-colaboradores-titulo: { es: Colaboradores, en: Colaboradores}
listado-proyectos-colaboradores-subtitulo: { es: en este proyecto colaboramos con, en: we work with}


listado-blog-categorias-titulo: { es: Ver artículos, en: List articles}
listado-blog-categorias-subtitulo: { es: por categoría, en: by category}

listado-enlaces-prensa-titulo: { es: Referencias en medios, en: References en medios}
listado-enlaces-prensa-subtitulo: { es: Sobre este proyecto, en: in media}

listado-reacciones-titulo: { es: Reacciones en Twitter, en: Twitter's reactions}
listado-reacciones-subtitulo: { es: , en:  }

listado-reacciones-articulo-texto: { es: Comenta este artículo con nosotros @colaborativaeu, en: Comment this article with us @colaborativaeu }
listado-reacciones-proyecto-texto: { es: Comenta este proyecto con nosotros @colaborativaeu, en: Comment this project with us @colaborativaeu }

inline-articulos: { es: artículo, en: article}
inline-en: { es: en, en: in}
inline-por: { es: por, en: by}
inline-y: { es: y, en: "&"}
inline-proyectos: { es: proyecto, en: project}
inline-auto-traduccion: { es: traducción automática, en: automated translation }
inline-leermas: { es: "<leer más>", en: "<read more>" }

proyectos-descripcion: { es: "Descripción", en: "Description" }
proyectos-imagenes: { es: "Imágenes", en: "Images" }
proyectos-reacciones: { es: "Reacciones", en: "Reactions" }
proyectos-reacciones-redes: { es: "Reacciones en redes sociales", en: "Reactions in social networks" }
proyectos-reacciones-twitter: { es: "n menciones en Twitter, tres últimos tweets", en: "n mentions in Twitter, three last tweets" }
proyectos-reacciones-resto: { es: "n menciones en el resto de redes sociales", en: "n mentions in other social networks" }
proyectos-reacciones-prensa:  { es: "Reacciones en prensa", en: "Reactions in press" }
