auto: false
server: false
lsi: false
markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
title: Turbulence Structure Laboratory
baseurl: /~alexlib/efdl/
github_user: turbulencelab