auto: false
server: false
lsi: false
markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "README.md", "CNAME"]
title: Turbulence Structure Laboratory
url: http://turbulencelab.github.com
github_user: turbulencelab